# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import marketplace_pb2 as common_dot_marketplace__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/marketplace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
                '/marketplace.CustomerService/CreateAccount',
                request_serializer=common_dot_marketplace__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/marketplace.CustomerService/Login',
                request_serializer=common_dot_marketplace__pb2.LoginRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ValidateSession = channel.unary_unary(
                '/marketplace.CustomerService/ValidateSession',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.ValidateSessionResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/marketplace.CustomerService/Logout',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.AddItemToCart = channel.unary_unary(
                '/marketplace.CustomerService/AddItemToCart',
                request_serializer=common_dot_marketplace__pb2.CartItemRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.CartModifyResponse.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/marketplace.CustomerService/RemoveFromCart',
                request_serializer=common_dot_marketplace__pb2.CartItemRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.CartModifyResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/marketplace.CustomerService/ClearCart',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.CartModifyResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/marketplace.CustomerService/SaveCart',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.CartModifyResponse.FromString,
                _registered_method=True)
        self.UpdateSellerFeedback = channel.unary_unary(
                '/marketplace.CustomerService/UpdateSellerFeedback',
                request_serializer=common_dot_marketplace__pb2.UpdateSellerFeedbackRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.UpdateSellerFeedbackResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/marketplace.CustomerService/GetCart',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/marketplace.CustomerService/GetBuyerPurchases',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/marketplace.CustomerService/GetSellerRating',
                request_serializer=common_dot_marketplace__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/marketplace.CustomerService/MakePurchase',
                request_serializer=common_dot_marketplace__pb2.SessionRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.MakePurchaseResponse.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItemToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSellerFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=common_dot_marketplace__pb2.CreateAccountRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=common_dot_marketplace__pb2.LoginRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.LoginResponse.SerializeToString,
            ),
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.ValidateSessionResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.LogoutResponse.SerializeToString,
            ),
            'AddItemToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItemToCart,
                    request_deserializer=common_dot_marketplace__pb2.CartItemRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.CartModifyResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=common_dot_marketplace__pb2.CartItemRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.CartModifyResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.CartModifyResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.CartModifyResponse.SerializeToString,
            ),
            'UpdateSellerFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSellerFeedback,
                    request_deserializer=common_dot_marketplace__pb2.UpdateSellerFeedbackRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.UpdateSellerFeedbackResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.GetCartResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=common_dot_marketplace__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=common_dot_marketplace__pb2.SessionRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.MakePurchaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/CreateAccount',
            common_dot_marketplace__pb2.CreateAccountRequest.SerializeToString,
            common_dot_marketplace__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/Login',
            common_dot_marketplace__pb2.LoginRequest.SerializeToString,
            common_dot_marketplace__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/ValidateSession',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.ValidateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/Logout',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItemToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/AddItemToCart',
            common_dot_marketplace__pb2.CartItemRequest.SerializeToString,
            common_dot_marketplace__pb2.CartModifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/RemoveFromCart',
            common_dot_marketplace__pb2.CartItemRequest.SerializeToString,
            common_dot_marketplace__pb2.CartModifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/ClearCart',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.CartModifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/SaveCart',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.CartModifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSellerFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/UpdateSellerFeedback',
            common_dot_marketplace__pb2.UpdateSellerFeedbackRequest.SerializeToString,
            common_dot_marketplace__pb2.UpdateSellerFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/GetCart',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/GetBuyerPurchases',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/GetSellerRating',
            common_dot_marketplace__pb2.GetSellerRatingRequest.SerializeToString,
            common_dot_marketplace__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerService/MakePurchase',
            common_dot_marketplace__pb2.SessionRequest.SerializeToString,
            common_dot_marketplace__pb2.MakePurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterItemForSale = channel.unary_unary(
                '/marketplace.ProductService/RegisterItemForSale',
                request_serializer=common_dot_marketplace__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.RegisterItemResponse.FromString,
                _registered_method=True)
        self.ChangeItemPrice = channel.unary_unary(
                '/marketplace.ProductService/ChangeItemPrice',
                request_serializer=common_dot_marketplace__pb2.ChangePriceRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.ChangePriceResponse.FromString,
                _registered_method=True)
        self.UpdateUnitsForSale = channel.unary_unary(
                '/marketplace.ProductService/UpdateUnitsForSale',
                request_serializer=common_dot_marketplace__pb2.UpdateUnitsRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.UpdateUnitsResponse.FromString,
                _registered_method=True)
        self.DisplayItemsForSale = channel.unary_unary(
                '/marketplace.ProductService/DisplayItemsForSale',
                request_serializer=common_dot_marketplace__pb2.SellerItemsRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.ItemListResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.ProductService/GetItem',
                request_serializer=common_dot_marketplace__pb2.GetItemRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.ProvideFeedback = channel.unary_unary(
                '/marketplace.ProductService/ProvideFeedback',
                request_serializer=common_dot_marketplace__pb2.ProvideFeedbackRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.ProvideFeedbackResponse.FromString,
                _registered_method=True)
        self.SearchItemsForSale = channel.unary_unary(
                '/marketplace.ProductService/SearchItemsForSale',
                request_serializer=common_dot_marketplace__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=common_dot_marketplace__pb2.ItemListResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterItemForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnitsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItemsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItemsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterItemForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItemForSale,
                    request_deserializer=common_dot_marketplace__pb2.RegisterItemRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.RegisterItemResponse.SerializeToString,
            ),
            'ChangeItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeItemPrice,
                    request_deserializer=common_dot_marketplace__pb2.ChangePriceRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.ChangePriceResponse.SerializeToString,
            ),
            'UpdateUnitsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnitsForSale,
                    request_deserializer=common_dot_marketplace__pb2.UpdateUnitsRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.UpdateUnitsResponse.SerializeToString,
            ),
            'DisplayItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItemsForSale,
                    request_deserializer=common_dot_marketplace__pb2.SellerItemsRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.ItemListResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=common_dot_marketplace__pb2.GetItemRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.GetItemResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=common_dot_marketplace__pb2.ProvideFeedbackRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.ProvideFeedbackResponse.SerializeToString,
            ),
            'SearchItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItemsForSale,
                    request_deserializer=common_dot_marketplace__pb2.SearchItemsRequest.FromString,
                    response_serializer=common_dot_marketplace__pb2.ItemListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterItemForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/RegisterItemForSale',
            common_dot_marketplace__pb2.RegisterItemRequest.SerializeToString,
            common_dot_marketplace__pb2.RegisterItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/ChangeItemPrice',
            common_dot_marketplace__pb2.ChangePriceRequest.SerializeToString,
            common_dot_marketplace__pb2.ChangePriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnitsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/UpdateUnitsForSale',
            common_dot_marketplace__pb2.UpdateUnitsRequest.SerializeToString,
            common_dot_marketplace__pb2.UpdateUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/DisplayItemsForSale',
            common_dot_marketplace__pb2.SellerItemsRequest.SerializeToString,
            common_dot_marketplace__pb2.ItemListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/GetItem',
            common_dot_marketplace__pb2.GetItemRequest.SerializeToString,
            common_dot_marketplace__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/ProvideFeedback',
            common_dot_marketplace__pb2.ProvideFeedbackRequest.SerializeToString,
            common_dot_marketplace__pb2.ProvideFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductService/SearchItemsForSale',
            common_dot_marketplace__pb2.SearchItemsRequest.SerializeToString,
            common_dot_marketplace__pb2.ItemListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
